# SPDX-FileCopyrightText: Copyright 2026, macmpi
# SPDX-License-Identifier: MIT

# Tiny mDNS announcer configuration

# HOSTNAME.local to be announced (default is system's)
#HOSTNAME=my-host

# Optionally announce services (default 0: none)
#ADVERTISE_HTTP=0
#ADVERTISE_SSH=0

# HTTP service options defaults
#HTTP_PORT=80
#HTTP_PATH="/"

# SSH service options
#SSH_PORT=22


##### Other implementation settings

# Announcements interval in seconds (default 60)
#INTERVAL=60

# Enable IPv6 announcements (default is 1)
#ADVERTISE_IPV6=1

# Use nc -s, default 1 (may depend on busybox versions)
#USE_SOURCE_ADDRESS=1

# Log each announcement (default is 0)
#DEBUG_LOG=0
