# SPDX-FileCopyrightText: Copyright 2026, macmpi
# SPDX-License-Identifier: MIT

# Tiny mDNS announcer configuration

HOST="$HOSTNAME"

# Set Optional services to be announced
#HTTP=80
#SSH=22

# OPTS list construction
OPTS="${HOST:+"--host \"${HOST}\""}"
OPTS="${OPTS} ${HTTP:+"--http=\"${HTTP}\""}"
OPTS="${OPTS} ${SSH:+"--ssh=\"${SSH}\""}"
